-- AlterTable
ALTER TABLE "UserProfile" ADD COLUMN     "isInGame" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lastSeen" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "showPresence" BOOLEAN NOT NULL DEFAULT true;
