-- AlterEnum
ALTER TYPE "NotificationCategory" ADD VALUE 'MARKET';

-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'MARKET_OFFER_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE 'MARKET_RESERVED';
ALTER TYPE "NotificationType" ADD VALUE 'MARKET_RESERVATION_ENDED';
ALTER TYPE "NotificationType" ADD VALUE 'MARKET_OFFER_ANSWERED';
ALTER TYPE "NotificationType" ADD VALUE 'MARKET_SOLD';
ALTER TYPE "NotificationType" ADD VALUE 'MARKET_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE 'MARKET_ARCHIVED';
ALTER TYPE "NotificationType" ADD VALUE 'MARKET_REPORT_OPENED';
