global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sigilos-beta'
    static_configs:
      - targets: ['sigilos-beta:3000']

  - job_name: 'sigilos-prod'
    static_configs:
      - targets: ['sigilos-prod:3000']
