#!/bin/bash
echo "=== AUDIT VPS SIGILOS ==="
echo ""
echo "1. CRON JOBS"
echo "─────────────"
crontab -l
echo ""
echo "2. ESPACE DISQUE"
echo "─────────────────"
df -h | grep -E "Filesystem|/$"
echo ""
echo "3. DOCKER CONTAINERS"
echo "────────────────────"
sudo docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Size}}"
echo ""
echo "4. SSH CONFIG"
echo "─────────────"
sudo grep -E "PermitRootLogin|PasswordAuthentication" /etc/ssh/sshd_config
echo ""
echo "5. FIREWALL"
echo "───────────"
sudo ufw status
echo ""
echo "6. FAIL2BAN"
echo "───────────"
sudo systemctl is-active fail2ban || echo "fail2ban non actif"
echo ""
echo "7. MAJ AUTO"
echo "───────────"
dpkg -l | grep unattended-upgrades || echo "unattended-upgrades non installé"
echo ""
echo "8. DOCKER CLEANUP (Gain Potentiel)"
echo "──────────────────────────────────"
sudo docker system df
echo ""
echo "=== FIN AUDIT ==="